-- GENERATED by scripts/gen-lua-rules.ts from src/lib/market-rules.ts.
-- Do NOT edit by hand: run `npm run gen:lua-rules`. The market rules and
-- the pipeline version live in one place (the TS module) so the terminal
-- and the in-game radar can never classify the same scan differently.
local ADDON_NAME, WAH = ...

WAH.PIPELINE_VERSION = 3

WAH.RADAR = {
  minProfit = 30,
  minProfitRatio = 0.25,
  discount = 0.85,
  minAuctions = 3,
  minHistory = 3,
  minMed7Distinct = 2,
  maxDiscount = 0.75,
  supplyShrink = false,
  supplyShrinkMax = -0.15,
  minAuctionsBoost = false,
  minAuctionsFloor = 5,
  supplyCap = 0
}
