// Compiles the single source of truth (src/lib/market-rules.ts) into the
// Lua constants the in-game addon reads. The addon has no build step, so
// the output is committed to the repo; scripts/gen-lua-rules.test.ts fails
// if the committed file drifts from this generator. Regenerate with:
//   npm run gen:lua-rules
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SCAN_PIPELINE_VERSION, dealRadarRules } from "@/lib/market-rules";

const LUA_PATH = fileURLToPath(new URL("../addon/WoWderhoiAH/GeneratedRules.lua", import.meta.url));

export function generateLuaRules(): string {
  const {
    minProfit, minProfitRatio, discount, minAuctions, minHistory, minMed7Distinct, maxDiscount,
    supplyShrink, supplyShrinkMax, minAuctionsBoost, minAuctionsFloor, supplyCap
  } = dealRadarRules;
  return `-- GENERATED by scripts/gen-lua-rules.ts from src/lib/market-rules.ts.
-- Do NOT edit by hand: run \`npm run gen:lua-rules\`. The market rules and
-- the pipeline version live in one place (the TS module) so the terminal
-- and the in-game radar can never classify the same scan differently.
local ADDON_NAME, WAH = ...

WAH.PIPELINE_VERSION = ${SCAN_PIPELINE_VERSION}

WAH.RADAR = {
  minProfit = ${minProfit},
  minProfitRatio = ${minProfitRatio},
  discount = ${discount},
  minAuctions = ${minAuctions},
  minHistory = ${minHistory},
  minMed7Distinct = ${minMed7Distinct},
  maxDiscount = ${maxDiscount},
  supplyShrink = ${supplyShrink},
  supplyShrinkMax = ${supplyShrinkMax},
  minAuctionsBoost = ${minAuctionsBoost},
  minAuctionsFloor = ${minAuctionsFloor},
  supplyCap = ${supplyCap}
}
`;
}

// CLI entry: write the file. Guarded so importing the generator (the test)
// does not touch disk.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(LUA_PATH, generateLuaRules());
  console.log(`Wrote ${LUA_PATH}`);
}
