// One-shot seed: replaces the Recipe table with the WoW: Forever (无限服)
// crafting library built from wx-wow.com — community client DB2 mining of
// build 1.60.1.69913 (fetched 2026-09-18):
//   - craft    1953 professional craft recipes (12 professions, native zh names)
//   - merchant  290 merchant-favor exchanges (集市商人 · 商人青睐, 8 professions)
// Data generated by scripts/build-wx-seed.mjs from the site's data-prof.js /
// data-kov.js / data-item.js dumps (see .tmp-wx-src/).
//
// It DELETES every existing Recipe row first — the previous classic 1.12
// English-name seed (1113 rows) is retired by user decision ("整个网站都是无限
// 服的，把你原来数据库的删掉吧"). In-game /wahrecipes scans continue to upsert
// over same (name, profession) rows; imported scans are categorized "craft".
//
// Run:  npx tsx scripts/seed-wx-recipes.ts
import { readFileSync } from "node:fs";
import { prisma } from "@/lib/prisma";

process.loadEnvFile();

type SeedMaterial = { itemId: number; name: string; quantity: number; quality?: number; ilvl?: number; req?: number };
type SeedRecipe = {
  name: string;
  profession: string;
  skillLevel: number;
  reagents: SeedMaterial[];
  outputs: SeedMaterial[];
  category?: string;
  favorCost?: number;
  difficulty?: number[];
  categoryName?: string;
  spellId?: number;
};

const file = new URL("../scripts/data/wx-recipes.json", import.meta.url);
const recipes = JSON.parse(readFileSync(file, "utf8")) as SeedRecipe[];
if (!Array.isArray(recipes) || recipes.length === 0) {
  throw new Error("scripts/data/wx-recipes.json is empty — rebuild it with scripts/build-wx-seed.mjs");
}

// Wipe the old library (classic 1.12 English seed + any prior rows), then seed.
const before = await prisma.recipe.count();
const deleted = await prisma.recipe.deleteMany({});
const results = await prisma.$transaction(
  recipes.map((r) =>
    prisma.recipe.create({
      data: {
        name: r.name,
        profession: r.profession,
        skillLevel: r.skillLevel,
        category: r.category === "merchant" ? "merchant" : "craft",
        favorCost: r.category === "merchant" ? (r.favorCost ?? 0) : 0,
        difficulty: r.difficulty ? (r.difficulty as unknown as object) : undefined,
        categoryName: r.categoryName || undefined,
        spellId: r.spellId || undefined,
        reagents: r.reagents as unknown as object,
        outputs: r.outputs as unknown as object
      }
    })
  )
);
const after = await prisma.recipe.count();
const byCategory = await prisma.recipe.groupBy({ by: ["category"], _count: true });

console.log(`seed done: deleted ${deleted.count} (was ${before}), created ${results.length}; Recipe table now has ${after} rows`);
console.log("by category:", JSON.stringify(byCategory));
await prisma.$disconnect();
